from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1500, 1015)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 300, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.title_lable = QtWidgets.QLabel(self.groupBox)
        self.title_lable.setGeometry(QtCore.QRect(50, 40, 221, 19))
        self.title_lable.setObjectName("title_lable")
        self.input_lable = QtWidgets.QLabel(self.centralwidget)
        self.input_lable.setGeometry(QtCore.QRect(30, 150, 221, 26))
        self.input_lable.setObjectName("input_lable")
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(30, 190, 300, 40))
        self.name_input.setObjectName("name_input")
        self.type_lable = QtWidgets.QLabel(self.centralwidget)
        self.type_lable.setGeometry(QtCore.QRect(30, 260, 221, 26))
        self.type_lable.setObjectName("type_lable")
        self.type_combo = QtWidgets.QComboBox(self.centralwidget)
        self.type_combo.setGeometry(QtCore.QRect(30, 300, 300, 40))
        self.type_combo.setObjectName("type_combo")
        self.level_lable = QtWidgets.QLabel(self.centralwidget)
        self.level_lable.setGeometry(QtCore.QRect(30, 360, 221, 26))
        self.level_lable.setObjectName("level_lable")
        self.easy = QtWidgets.QRadioButton(self.centralwidget)
        self.easy.setGeometry(QtCore.QRect(30, 410, 250, 35))
        self.easy.setObjectName("easy")
        self.medium = QtWidgets.QRadioButton(self.centralwidget)
        self.medium.setGeometry(QtCore.QRect(150, 410, 250, 35))
        self.medium.setObjectName("medium")
        self.hard = QtWidgets.QRadioButton(self.centralwidget)
        self.hard.setGeometry(QtCore.QRect(30, 460, 250, 35))
        self.hard.setObjectName("hard")
        self.age_lable = QtWidgets.QLabel(self.centralwidget)
        self.age_lable.setGeometry(QtCore.QRect(30, 520, 221, 26))
        self.age_lable.setObjectName("age_lable")
        self.age_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.age_spin.setGeometry(QtCore.QRect(30, 560, 200, 40))
        self.age_spin.setObjectName("age_spin")
        self.health_lable = QtWidgets.QLabel(self.centralwidget)
        self.health_lable.setGeometry(QtCore.QRect(30, 620, 221, 26))
        self.health_lable.setObjectName("health_lable")
        self.health_combo = QtWidgets.QComboBox(self.centralwidget)
        self.health_combo.setGeometry(QtCore.QRect(30, 660, 300, 40))
        self.health_combo.setObjectName("health_combo")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(30, 730, 300, 40))
        self.add_btn.setObjectName("add_btn")
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setGeometry(QtCore.QRect(30, 790, 300, 40))
        self.reset_btn.setObjectName("reset_btn")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(350, 30, 1080, 880))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(750, 920, 300, 35))
        self.delete_btn.setObjectName("delete_btn")
        self.nim_lable = QtWidgets.QLabel(self.centralwidget)
        self.nim_lable.setGeometry(QtCore.QRect(1380, 10, 102, 18))
        self.nim_lable.setObjectName("nim_lable")
        self.nim_lable.setStyleSheet("color: gray; font-size: 18px;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plant Collection - F1D022096"))
        self.title_lable.setText(_translate("MainWindow", "KOLEKSI TANAMAN"))
        self.input_lable.setText(_translate("MainWindow", "Nama Tanaman:"))
        self.type_lable.setText(_translate("MainWindow", "Jenis Tanaman:"))
        self.level_lable.setText(_translate("MainWindow", "Tingkat Perawatan:"))
        self.easy.setText(_translate("MainWindow", "Mudah"))
        self.medium.setText(_translate("MainWindow", "Sedang"))
        self.hard.setText(_translate("MainWindow", "Sulit"))
        self.age_lable.setText(_translate("MainWindow", "Usia Tanaman (bulan):"))
        self.health_lable.setText(_translate("MainWindow", "Kesehatan Tanaman:"))
        self.add_btn.setText(_translate("MainWindow", "Add"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.delete_btn.setText(_translate("MainWindow", "Delete Selected"))
        self.nim_lable.setText(_translate("MainWindow", "F1D022096"))
